Fix resolving of relative URL filenames (fixes Debian bug 748905)
urlwatch fails with exception if the URL filename doesn't include the /
character. So this works:

$ urlwatch --urls=./urls

But this, which should be equivalent, doesn't:

$ urlwatch --urls=urls
Traceback (most recent call last):
 File "/usr/bin/urlwatch", line 244, in <module>
   jobs = handler.parse_urls_txt(urls_txt)
 File "/usr/share/urlwatch/urlwatch/handler.py", line 155, in parse_urls_txt
   dir_st = os.stat(dirname)
OSError: [Errno 2] No such file or directory: ''

Thanks to Jakub Wilk for reporting this issue here:
https://bugs.debian.org/748905